# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a52e48092d3e8bf1f83f7ad1f5a1d98479cb89418f596084af356b2d137e94f6617972005b00e0fde3f5da575b0f6af26c203a1b9c83e2a1f10d4ccf129bf646

test:
  secret_key_base: 7286688e4fc4f1166027b1437e562d02519ece7244c34f4e2ac4398205126810de1dcebf5db642d6fae9a03ab37bfba1f180d193dc2ff3b57db40fad3e630fb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
